title: Dev log of Battle Flows
author: GitHub User
email: tbd@invalid
description: > # this means to ignore newlines until "baseurl:"
  Real-time-strategy game in development where you create supply flows of troops to battle your opponent for control of the terrain. Based on the classic XBattle.

# social links
twitter_username: BattleFlowsGame # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
